In [4]:
### Numpy
# 고성능 수치 계산을 위해 제작된 파이썬 라이브러리
# 머신러닝/딥러닝 알고리즘은 기본적으로 다차원 배열에 대한 계산으로 볼 수 있음
# 혹은 대량 데이터를 다룰 때 빠른 계산 능력이 요구되기 때문에 사용하는 라이브러리
# 핵심 객체 : ndarray

# 생성된 Numpy 확인
import numpy as np
temp = np.array([1,2,3])
print(type(temp))       # <class 'numpy.ndarray'>

# 튜토리얼 : https://numpy.org/doc/stable/user/quickstart.html

<class 'numpy.ndarray'>


In [11]:
# NumPy 기본 문법

# list
data1 = [1,2,3]
data1       # [1, 2, 3]

data2 = [1,1,2,2,3,4]
data2       # [1, 1, 2, 2, 3, 4]

# np.array로 배열 전환
my_array1 = np.array(data1)
print(my_array1)        # [1 2 3]   -> 구분자가 ,가 아닌 공백!
print(my_array1.shape)  # (3,)

my_array2 = np.array(data2)
print(my_array2)        # [1 1 2 2 3 4]
print(my_array2.shape)  # (6,)

# shape : 크기를 확인하는 함수

# 리스트 선언 없이 바로 np.array로 사용
my_array3 = np.array([3,4,5,12])
print(my_array3.dtype)  # int32

## Numpy의 Data Types 참조 : https://numpy.org/devdocs/user/basics.types.html 

[1 2 3]
(3,)
[1 1 2 2 3 4]
(6,)
int32


In [14]:
# 2차 배열
my_array4 = np.array([[2,4,6],[8,10,12],[14,16,18],[20,22,24]])
my_array4
my_array4.shape     # (4, 3)

# 3차 배열
my_array5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
my_array5.shape     # (2, 2, 2)

(2, 2, 2)

In [20]:
### Numpy 배열 생성 및 둘러보기
# Arrange : Range 함수와 유사하며, 배열을 쉽게 만들 수 있음
arange_array = np.arange(5)    # arange(start, stop, step, , dtype, ...)
print(arange_array)             # [0 1 2 3 4]

arange_array2 = np.arange(1,9)
print(arange_array2)            # [1 2 3 4 5 6 7 8]

arange_array3 = np.arange(1,9,3)
print(arange_array3)            # [1 4 7]

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 4 7]


In [27]:
### Zeros, Ones - 0으로 채우기, 1로 채우기
# 할당하는 사이즈 배열에 0이나 1로 쉽게 초기화하는 함수
zeros_arr = np.zeros((3,2))
print(zeros_arr)
print("Data Type :",zeros_arr.dtype)        # Data Type : float64 (기본 데이터타입은 float)
print("Data Shape :",zeros_arr.shape)

ones_arr = np.ones((3,4), dtype="int32")
print(ones_arr)
print("Data Type :",ones_arr.dtype)        # Data Type : int32
print("Data Shape :",ones_arr.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data Type : float64
Data Shape : (3, 2)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data Type : int32
Data Shape : (3, 4)


In [43]:
## Reshape - 사이즈는 기존과 동일해야 함 (3*4 = 6*2)
after_reshape = ones_arr.reshape(6,2)
print(after_reshape)
print("Data Shape :", after_reshape.shape)
print('-'*40)
# ones_arr를 사이즈 변경해보기
print(ones_arr.reshape(2,2,3))
print('-'*40)
print(ones_arr.reshape(1,12))
print('-'*40)
print(ones_arr.reshape(1,3,4))
print('-'*40)

# reshape에서 -1은 차원을 자동으로 계산!
after_reshape = ones_arr.reshape(-1,6)
print(after_reshape)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape : (6, 2)
----------------------------------------
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
----------------------------------------
[[1 1 1 1 1 1 1 1 1 1 1 1]]
----------------------------------------
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
----------------------------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [50]:
### NumPy 인덱싱과 슬라이싱
my_array = np.arange(0, 4)
print(my_array)     # [0 1 2 3]

print('my_array의 첫번째 요소는',my_array[0])
print('my_array[0:3]은', my_array[0:3])
print('my_array[:]은', my_array[:])
print('my_array[-3:-1]은', my_array[-3:-1])

[0 1 2 3]
my_array의 첫번째 요소는 0
my_array[0:3]은 [0 1 2]
my_array[:]은 [0 1 2 3]
my_array[0:-1]은 [1 2]


In [58]:
my_array2 = np.array([
    [2,4,6,8,10,12,14,16,18],
     [3,6,9,12,15,18,21,24,27],
     [4,8,12,16,20,24,28,32,36],
     [5,10,15,20,25,30,35,40,45]
])
print(my_array2.shape)
print(my_array2[2:4,3:5])   # [행, 열]
print(my_array2[1:3,:])

(4, 9)
[[16 20]
 [20 25]]
[[ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]]


In [65]:
# NumPy 정렬 : sort(), argsort()

# np.sort()
height_arr = np.array([174,165,182,180,168])
sorted_height_arr = np.sort(height_arr)

print('Height Matrix :',height_arr)
print('np.sort() Matrix :',sorted_height_arr)

# 내림차순
desc_height_arr = np.sort(height_arr)[::-1]
print('np.sort()[::-1] :', desc_height_arr)

# argsort() : 지정된 축을 따라 인덱스의 배열을 반환하도록 하는, 지정된 종류의 정렬을 사용해 입력 배열에서 간접 정렬을 수행
fives = np.array([10,5,15,20])
fives_order = fives.argsort()   # 인덱스값으로 이루어진 배열 반환
print('argsort() :',fives_order)    # 배열값을 오름차순으로 인덱싱
print('Ascending :',fives[fives_order])

# NumPyTutorials : https://numpy.org/learn/
# NumPy Broadcasting : https://numpy.org/doc/stable/user/basics.broadcasting.html

# 숙제 : 같은 크기의 두 배열에 대한 연산, 서로 크기가 다른 두 배열의 연산 공부하기~

Height Matrix : [174 165 182 180 168]
np.sort() Matrix : [165 168 174 180 182]
np.sort()[::-1] : [182 180 174 168 165]
argsort() : [1 0 2 3]
Ascending : [ 5 10 15 20]
